// Mocks generated by Mockito 5.4.6 from annotations
// in agenda_treinamento/test/domain/usecases/lista_espera/lista_espera_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:agenda_treinamento/domain/entities/lista_espera.dart' as _i4;
import 'package:agenda_treinamento/domain/repositories/lista_espera_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ListaEsperaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListaEsperaRepository extends _i1.Mock
    implements _i2.ListaEsperaRepository {
  MockListaEsperaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.ListaEspera>> getListaEspera() =>
      (super.noSuchMethod(
            Invocation.method(#getListaEspera, []),
            returnValue: _i3.Stream<List<_i4.ListaEspera>>.empty(),
          )
          as _i3.Stream<List<_i4.ListaEspera>>);

  @override
  _i3.Future<void> adicionarListaEspera(_i4.ListaEspera? item) =>
      (super.noSuchMethod(
            Invocation.method(#adicionarListaEspera, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removerListaEspera(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removerListaEspera, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateListaEspera(_i4.ListaEspera? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateListaEspera, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
