// Mocks generated by Mockito 5.4.6 from annotations
// in agenda_treinamento/test/domain/usecases/pagamento/reverter_pagamento_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:agenda_treinamento/domain/entities/pagamento.dart' as _i4;
import 'package:agenda_treinamento/domain/entities/sessao.dart' as _i7;
import 'package:agenda_treinamento/domain/entities/treinamento.dart' as _i10;
import 'package:agenda_treinamento/domain/repositories/pagamento_repository.dart'
    as _i2;
import 'package:agenda_treinamento/domain/repositories/sessao_repository.dart'
    as _i6;
import 'package:agenda_treinamento/domain/repositories/treinamento_repository.dart'
    as _i9;
import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PagamentoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPagamentoRepository extends _i1.Mock
    implements _i2.PagamentoRepository {
  MockPagamentoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Pagamento>> getPagamentos() =>
      (super.noSuchMethod(
            Invocation.method(#getPagamentos, []),
            returnValue: _i3.Stream<List<_i4.Pagamento>>.empty(),
          )
          as _i3.Stream<List<_i4.Pagamento>>);

  @override
  _i3.Stream<List<_i4.Pagamento>> getPagamentosByTreinamentoId(
    String? treinamentoId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPagamentosByTreinamentoId, [treinamentoId]),
            returnValue: _i3.Stream<List<_i4.Pagamento>>.empty(),
          )
          as _i3.Stream<List<_i4.Pagamento>>);

  @override
  _i3.Future<String> addPagamento(_i4.Pagamento? pagamento) =>
      (super.noSuchMethod(
            Invocation.method(#addPagamento, [pagamento]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addPagamento, [pagamento]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updatePagamento(_i4.Pagamento? pagamento) =>
      (super.noSuchMethod(
            Invocation.method(#updatePagamento, [pagamento]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePagamento(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePagamento, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SessaoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessaoRepository extends _i1.Mock implements _i6.SessaoRepository {
  MockSessaoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i7.Sessao>> getSessoes() =>
      (super.noSuchMethod(
            Invocation.method(#getSessoes, []),
            returnValue: _i3.Stream<List<_i7.Sessao>>.empty(),
          )
          as _i3.Stream<List<_i7.Sessao>>);

  @override
  _i3.Stream<List<_i7.Sessao>> getSessoesByTreinamentoId(
    String? treinamentoId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessoesByTreinamentoId, [treinamentoId]),
            returnValue: _i3.Stream<List<_i7.Sessao>>.empty(),
          )
          as _i3.Stream<List<_i7.Sessao>>);

  @override
  _i3.Future<List<_i7.Sessao>> getSessoesByTreinamentoIdOnce(
    String? treinamentoId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessoesByTreinamentoIdOnce, [treinamentoId]),
            returnValue: _i3.Future<List<_i7.Sessao>>.value(<_i7.Sessao>[]),
          )
          as _i3.Future<List<_i7.Sessao>>);

  @override
  _i3.Stream<List<_i7.Sessao>> getSessoesByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSessoesByDate, [date]),
            returnValue: _i3.Stream<List<_i7.Sessao>>.empty(),
          )
          as _i3.Stream<List<_i7.Sessao>>);

  @override
  _i3.Stream<List<_i7.Sessao>> getSessoesByMonth(DateTime? monthDate) =>
      (super.noSuchMethod(
            Invocation.method(#getSessoesByMonth, [monthDate]),
            returnValue: _i3.Stream<List<_i7.Sessao>>.empty(),
          )
          as _i3.Stream<List<_i7.Sessao>>);

  @override
  _i3.Future<void> setDayBlockedStatus(DateTime? date, bool? isBlocked) =>
      (super.noSuchMethod(
            Invocation.method(#setDayBlockedStatus, [date, isBlocked]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> addSessao(_i7.Sessao? sessao) =>
      (super.noSuchMethod(
            Invocation.method(#addSessao, [sessao]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addSessao, [sessao]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> addMultipleSessoes(List<_i7.Sessao>? sessoes) =>
      (super.noSuchMethod(
            Invocation.method(#addMultipleSessoes, [sessoes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSessao(_i7.Sessao? sessao) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessao, [sessao]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSessao(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSessao, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMultipleSessoes(List<String>? sessaoIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMultipleSessoes, [sessaoIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addSessaoInBatch(_i8.WriteBatch? batch, _i7.Sessao? sessao) =>
      super.noSuchMethod(
        Invocation.method(#addSessaoInBatch, [batch, sessao]),
        returnValueForMissingStub: null,
      );

  @override
  void updateSessaoInBatch(_i8.WriteBatch? batch, _i7.Sessao? sessao) =>
      super.noSuchMethod(
        Invocation.method(#updateSessaoInBatch, [batch, sessao]),
        returnValueForMissingStub: null,
      );

  @override
  void deleteSessaoInBatch(_i8.WriteBatch? batch, String? sessaoId) =>
      super.noSuchMethod(
        Invocation.method(#deleteSessaoInBatch, [batch, sessaoId]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TreinamentoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreinamentoRepository extends _i1.Mock
    implements _i9.TreinamentoRepository {
  MockTreinamentoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i10.Treinamento>> getTreinamentos() =>
      (super.noSuchMethod(
            Invocation.method(#getTreinamentos, []),
            returnValue: _i3.Stream<List<_i10.Treinamento>>.empty(),
          )
          as _i3.Stream<List<_i10.Treinamento>>);

  @override
  _i3.Future<_i10.Treinamento?> getTreinamentoById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTreinamentoById, [id]),
            returnValue: _i3.Future<_i10.Treinamento?>.value(),
          )
          as _i3.Future<_i10.Treinamento?>);

  @override
  _i3.Stream<List<_i10.Treinamento>> getTreinamentosByPacienteId(
    String? pacienteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTreinamentosByPacienteId, [pacienteId]),
            returnValue: _i3.Stream<List<_i10.Treinamento>>.empty(),
          )
          as _i3.Stream<List<_i10.Treinamento>>);

  @override
  _i3.Future<String> addTreinamento(_i10.Treinamento? treinamento) =>
      (super.noSuchMethod(
            Invocation.method(#addTreinamento, [treinamento]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addTreinamento, [treinamento]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateTreinamento(_i10.Treinamento? treinamento) =>
      (super.noSuchMethod(
            Invocation.method(#updateTreinamento, [treinamento]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasActiveTreinamento(String? pacienteId) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveTreinamento, [pacienteId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasOverlap(
    String? diaSemana,
    String? horario, {
    String? excludeTreinamentoId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasOverlap,
              [diaSemana, horario],
              {#excludeTreinamentoId: excludeTreinamentoId},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
